import React, { forwardRef } from "react";

const PrintableAttendanceReport = forwardRef(({ reportRecords, reportTitle, reportMeta }, ref) => {
    // Format display time
    const formatTime = (timeString) => {
        if (!timeString) return "-";
        return new Date(timeString).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    };

    // Format display duration
    const formatDuration = (minutes) => {
        if (minutes === null || minutes === undefined || minutes === 0) return "-";
        const hrs = Math.floor(minutes / 60);
        const mins = minutes % 60;
        if (hrs > 0) {
            return `${hrs}h ${mins}m`;
        }
        return `${mins}m`;
    };

    return (
        <div style={{ display: "none" }}>
            <div ref={ref} className="p-10 text-slate-800 bg-white font-sans w-full print-page">
                {/* Report Header */}
                <div className="flex justify-between items-center border-b-2 border-blue-600 pb-6 mb-8">
                    <div>
                        <h1 className="text-2xl font-black text-slate-900 tracking-tight">BLUEBIRD HOTELS</h1>
                        <p className="text-sm font-bold text-slate-700 uppercase tracking-widest mt-0.5">{reportTitle}</p>
                    </div>
                    <div className="text-right text-xs text-slate-500">
                        <p className="font-semibold text-slate-700">Date Generated:</p>
                        <p>{new Date().toLocaleString()}</p>
                        <p className="mt-1">Generated By: Administrator</p>
                    </div>
                </div>

                {/* Filters Summary */}
                <div className="bg-slate-50 rounded-2xl p-4 mb-6 border border-slate-100 flex flex-wrap gap-x-8 gap-y-2 text-xs">
                    <div>
                        <span className="font-bold text-slate-500 mr-1 uppercase">Report Scope / Period:</span>
                        <span className="text-slate-800 font-semibold">{reportMeta.dateRange}</span>
                    </div>
                    <div>
                        <span className="font-bold text-slate-500 mr-1 uppercase">Target Staff:</span>
                        <span className="text-slate-800 font-semibold">{reportMeta.search}</span>
                    </div>
                    <div>
                        <span className="font-bold text-slate-500 mr-1 uppercase">Total Records Compiled:</span>
                        <span className="text-slate-800 font-semibold">{reportRecords.length}</span>
                    </div>
                </div>

                {/* Stats Summary Panel */}
                <div className="grid grid-cols-5 gap-3 mb-8">
                    <div className="border border-slate-200 rounded-xl p-3 text-center bg-slate-50/30">
                        <p className="text-[10px] uppercase font-bold text-slate-400">Total Entries</p>
                        <h3 className="text-lg font-black text-slate-800 mt-1">{reportRecords.length}</h3>
                    </div>
                    <div className="border border-slate-200 rounded-xl p-3 text-center bg-slate-50/30">
                        <p className="text-[10px] uppercase font-bold text-slate-400">Total Hours Worked</p>
                        <h3 className="text-lg font-black text-indigo-600 mt-1">
                            {Number(reportRecords.reduce((sum, r) => sum + (r.workingHours || 0), 0).toFixed(2))}h
                        </h3>
                    </div>
                    <div className="border border-slate-200 rounded-xl p-3 text-center bg-slate-50/30">
                        <p className="text-[10px] uppercase font-bold text-slate-400">Present (On Time)</p>
                        <h3 className="text-lg font-black text-emerald-600 mt-1">
                            {reportRecords.filter(r => r.status === "Present").length}
                        </h3>
                    </div>
                    <div className="border border-slate-200 rounded-xl p-3 text-center bg-slate-50/30">
                        <p className="text-[10px] uppercase font-bold text-slate-400">Late Check-ins</p>
                        <h3 className="text-lg font-black text-amber-600 mt-1">
                            {reportRecords.filter(r => r.status === "Late").length}
                        </h3>
                    </div>
                    <div className="border border-slate-200 rounded-xl p-3 text-center bg-slate-50/30">
                        <p className="text-[10px] uppercase font-bold text-slate-400">Absent</p>
                        <h3 className="text-lg font-black text-rose-600 mt-1">
                            {reportRecords.filter(r => r.status === "Absent").length}
                        </h3>
                    </div>
                </div>

                {/* Table */}
                <table className="w-full text-left text-xs border-collapse">
                    <thead>
                        <tr className="border-b-2 border-slate-300 text-slate-500 font-bold uppercase tracking-wider">
                            <th className="py-2.5">Date</th>
                            <th className="py-2.5">Staff ID</th>
                            <th className="py-2.5">Staff Name</th>
                            <th className="py-2.5">Check In</th>
                            <th className="py-2.5">Check Out</th>
                            <th className="py-2.5">Worked Time</th>
                            <th className="py-2.5 text-center">Status</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                        {reportRecords.map((record, index) => (
                            <tr key={index} className="hover:bg-slate-50">
                                <td className="py-2.5 font-medium">{record.attendanceDate}</td>
                                <td className="py-2.5 font-bold text-slate-600">{record.staffId}</td>
                                <td className="py-2.5 font-semibold text-slate-700">{record.StaffMember?.name || "-"}</td>
                                <td className="py-2.5">{formatTime(record.checkInTime)}</td>
                                <td className="py-2.5">{formatTime(record.checkOutTime)}</td>
                                <td className="py-2.5">{formatDuration(record.workingMinutes)}</td>
                                <td className="py-2.5 text-center">
                                    <span className={`px-2 py-0.5 rounded font-bold border text-[10px] ${
                                        record.status === "Present"
                                            ? "bg-emerald-50 border-emerald-100 text-emerald-700"
                                            : record.status === "Late"
                                            ? "bg-amber-50 border-amber-100 text-amber-700"
                                            : "bg-rose-50 border-rose-100 text-rose-700"
                                    }`}>
                                        {record.status}
                                    </span>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>

                {/* Signature Area */}
                <div className="mt-16 pt-8 border-t border-slate-200 grid grid-cols-2 gap-8 text-xs text-slate-500">
                    <div>
                        <p className="font-bold text-slate-700">Verified By:</p>
                        <div className="border-b border-slate-300 w-48 h-12 mt-2"></div>
                        <p className="mt-1">Authorized HR Manager</p>
                    </div>
                    <div className="text-right flex flex-col items-end">
                        <p className="font-bold text-slate-700">Official Seal:</p>
                        <div className="border border-dashed border-slate-300 rounded-lg w-28 h-20 mt-2 flex items-center justify-center text-[9px]">
                            Place Seal Here
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
});

export default PrintableAttendanceReport;
